### ISSUE TITLE
How to use for a custom Detectron2 build?

### ISSUE THREAD

**Issue by justinkay** [MiroPsota/torch_packages_builder#2]
Hi @MiroPsota, I'm very interested in your work but unsure how to use it myself.

I'd like to build wheels for a variety of Torch/CUDA versions for a specific commit of Detectron2 I've forked here: https://github.com/justinkay/detectron2_v07ish

How would I go about using your code to do this?

**Comment by justinkay** [comment]
Nevermind - figured it out! Very easy, just copied everything here into my codebase and ran the workflow through Github Actions.

Thanks for the great work!

**Comment by MiroPsota** [comment]
I suggest forking this repository (with GitHub Pages set up), running GitHub Actions, and publishing wheels in the GitHub Releases as a starting point (although with no pip cache).

I don't recommend using PyPI as it's not suited for these types of packages. A good solution is to host it elsewhere and use `--index-url` as pytorch.org does, or suffixes as in this repository (since suffixes don't work with PyPI).

If you don't want to use the publishing pipeline in your repository, you should remove [this](https://github.com/MiroPsota/torch_packages_builder/blob/e8c942dff98225fde73e612431a48eabcbd12bb2/.github/workflows/build_wheels.yml#L188) and [this](https://github.com/MiroPsota/torch_packages_builder/blob/e8c942dff98225fde73e612431a48eabcbd12bb2/.github/workflows/build_wheels.yml#L225) part and write the rest yourself.

**Comment by justinkay** [comment]
Thanks for the reply and guidance. Yes, after some fussing, I came to the same conclusion about PyPI. Thanks again for your work.
